# Esimerkki CI/CD-workflow projektirepoon:
# T채m채 workflow buildaa projektin oman MkDocs-dokumentaation ja siirt채채 sen keskitettyyn dokumentaatiorepoon (esim. panualaluusua/docs)

name: Sync Docs to Central

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies (pip if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      - name: Install Poetry if pyproject.toml exists
        if: ${{ exists('pyproject.toml') }}
        run: pip install poetry
      - name: Install dependencies (Poetry)
        if: ${{ exists('pyproject.toml') }}
        run: poetry install --no-interaction --no-root
      - name: Checkout central documentation repository
        uses: actions/checkout@v4
        with:
          repository: panualaluusua/docs
          token: ${{ secrets.DOCS_PUSH_TOKEN }}
          path: central-docs
      - name: Get repository name
        id: vars
        run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
      - name: Sync docs
        run: |
          rsync -av --delete docs/ central-docs/docs/${REPO_NAME}/
          cd central-docs
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update project documentation from $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
